# Project: Shape
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Shape.o Rectangle.o Circle.o Cube.o Sphere.o
LINKOBJ  = main.o Shape.o Rectangle.o Circle.o Cube.o Sphere.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Shape.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Shape.o: Shape.cpp
	$(CPP) -c Shape.cpp -o Shape.o $(CXXFLAGS)

Rectangle.o: Rectangle.cpp
	$(CPP) -c Rectangle.cpp -o Rectangle.o $(CXXFLAGS)

Circle.o: Circle.cpp
	$(CPP) -c Circle.cpp -o Circle.o $(CXXFLAGS)

Cube.o: Cube.cpp
	$(CPP) -c Cube.cpp -o Cube.o $(CXXFLAGS)

Sphere.o: Sphere.cpp
	$(CPP) -c Sphere.cpp -o Sphere.o $(CXXFLAGS)
